/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as MlModelsRouteImport } from './routes/ml-models'
import { Route as RiskInvestigationRouteImport } from './routes/risk-investigation'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TransactionsRouteImport } from './routes/transactions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const MlModelsRoute = MlModelsRouteImport.update({
  id: '/ml-models',
  path: '/ml-models',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskInvestigationRoute = RiskInvestigationRouteImport.update({
  id: '/risk-investigation',
  path: '/risk-investigation',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/ml-models': typeof MlModelsRoute
  '/risk-investigation': typeof RiskInvestigationRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/ml-models': typeof MlModelsRoute
  '/risk-investigation': typeof RiskInvestigationRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/ml-models': typeof MlModelsRoute
  '/risk-investigation': typeof RiskInvestigationRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/ml-models'
    | '/risk-investigation'
    | '/settings'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/ml-models'
    | '/risk-investigation'
    | '/settings'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/ml-models'
    | '/risk-investigation'
    | '/settings'
    | '/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  MlModelsRoute: typeof MlModelsRoute
  RiskInvestigationRoute: typeof RiskInvestigationRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml-models': {
      id: '/ml-models'
      path: '/ml-models'
      fullPath: '/ml-models'
      preLoaderRoute: typeof MlModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-investigation': {
      id: '/risk-investigation'
      path: '/risk-investigation'
      fullPath: '/risk-investigation'
      preLoaderRoute: typeof RiskInvestigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  MlModelsRoute: MlModelsRoute,
  RiskInvestigationRoute: RiskInvestigationRoute,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
